# ----------------------------------------------------------------
# Fluid 主题专用配置文件
# ----------------------------------------------------------------

# 浏览器标签页图标 (Favicon)
favicon: /img/favicon.png
apple_touch_icon: /img/favicon.png

# 顶部菜单栏配置
navbar:
  blog_title: Auzsadong's Blog # 页面左上角的名称
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }

# ----------------------------------------------------------------
# 首页背景图 (Banner)
# ----------------------------------------------------------------
index:
#  banner_img: /img/home_bg.jpg  # 这里修改首页大图路径
#  banner_mask_alpha: 0.3        # 背景遮罩透明度 (0-1)，越大越暗
slogan: {
    enable: true,
    text: "Auzsadong 的硬件开发笔记", 
  }

# ----------------------------------------------------------------
# 文章页背景图
# ----------------------------------------------------------------
#post:
  #banner_img: /img/default.png  # 这里修改文章页默认大图
  #meta:
  #  author: { enable: true }
  #  date: { enable: true, format: "YYYY-MM-DD HH:mm" }

# ----------------------------------------------------------------
# 代码块高亮配置
# ----------------------------------------------------------------
code:
  copy_btn: true      # 显示复制按钮
  highlight:
    enable: true
    lib: 'highlightjs'
    style: 'Github Gist' # 你可以换成 'Atom One Dark' 等你喜欢的风格